# Docker
task: Docker@2
  inputs:
    containerRegistry: 'tenableio-consec'
    repository: 'azure-vuln-web-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker