task: Docker@2
  inputs:
    containerRegistry: 'tenableio-consec'
    repository: 'azure-pipeline'
    command: 'buildAndPush'
    Dockerfile: 'https://github.com/zerofai/mywebapp01/blob/azure-pipelines/Dockerfile'
    buildContext: 